# Generated by Django 5.1.4 on 2025-01-18 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('date_hired', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='TriadApp.stall')),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
    ]
