# Generated by Django 5.1.4 on 2025-01-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
    ]
