# Generated by Django 5.1.4 on 2025-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(default=1, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('stall', 'name', 'size')},
        ),
    ]
