# Generated by Django 5.1.4 on 2025-01-14 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='TriadApp.stall')),
            ],
        ),
    ]
