# Generated by Django 5.1.4 on 2025-01-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='raw_password',
            field=models.CharField(default='default123', max_length=50, verbose_name='Visible Password'),
        ),
    ]
