# Generated by Django 5.1.4 on 2025-01-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0002_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminProfile',
        ),
    ]
