# Generated by Django 5.1.4 on 2025-01-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0002_adminprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(max_length=1)),
                ('lastname', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TriadApp.stall')),
            ],
        ),
    ]
