# Generated by Django 5.1.4 on 2025-01-15 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0004_item_itemsupply'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='TriadApp.stall', to_field='store_id'),
        ),
    ]
