# Generated by Django 5.1.4 on 2025-01-14 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0004_stall_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='TriadApp.stall', to_field='store_id'),
        ),
    ]
