# Generated by Django 5.1.4 on 2025-01-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0004_transaction_transactionitem_transactionitemaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('maya', 'Maya')], default='cash', max_length=20),
        ),
    ]
