# Generated by Django 5.1.4 on 2025-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0005_item_stall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsupply',
            name='quantity',
        ),
        migrations.AddField(
            model_name='itemsupply',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
