# Generated by Django 5.1.4 on 2025-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0006_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='attempt_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='block_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
