# Generated by Django 5.1.4 on 2025-01-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0006_remove_itemsupply_quantity_itemsupply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='TriadApp.stall', to_field='store_id'),
        ),
    ]
