# Generated by Django 5.1.4 on 2025-01-19 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0007_stallcontract_stallpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='transaction_reports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='TriadApp.employee')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
