# Generated by Django 5.1.4 on 2025-01-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0007_loginhistory_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
