# Generated by Django 5.1.4 on 2025-01-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0008_transactionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('good', 'Good'), ('expired', 'Expired')], default='good', max_length=20),
        ),
    ]
