# Generated by Django 5.1.4 on 2025-01-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0008_loginhistory_browser_loginhistory_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='location',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='bios_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='firewall_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='gpu_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='processor_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
