# Generated by Django 5.1.4 on 2025-01-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0009_remove_loginhistory_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='bios_version',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='firewall_status',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
