# Generated by Django 5.1.4 on 2025-01-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0009_supply_expiration_date_supply_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stallpayment',
            name='payment_for_month',
        ),
        migrations.RemoveField(
            model_name='stallpayment',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='stallpayment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
