# Generated by Django 5.1.4 on 2025-01-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0010_remove_loginhistory_bios_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='wifi_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
