# Generated by Django 5.1.4 on 2025-01-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0010_remove_stallpayment_payment_for_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stallcontract',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='stallcontract',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stallcontract',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
