# Generated by Django 5.1.4 on 2025-01-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0011_remove_stallcontract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stallcontract',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='stallcontract',
            name='duration_months',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stallcontract',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
