# Generated by Django 5.1.4 on 2025-01-21 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0012_alter_stallcontract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contract_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
