# Generated by Django 5.1.4 on 2025-01-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriadApp', '0013_supplier_status_alter_supplier_contract_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10),
        ),
    ]
